---
    provisioner:
      name: terraform
    
    verifier:
      name: terraform
      systems:
        - name: inspec-gcp
          backend: gcp

    platforms:
      - name: terraform
    
    suites:
    #   - name: simple-cluster
    #     driver:
    #       name: terraform
    #       root_module_directory: examples/simple-cluster
    #       command_timeout: 12000
      - name: brown-modules-cluster
        driver:
          name: terraform
          root_module_directory: examples/brown-modules-cluster
          command_timeout: 12000