---
    provisioner:
      name: terraform
    
    verifier:
      name: terraform
      systems:
        - name: inspec-gcp
          backend: gcp

    platforms:
      - name: terraform
    
    suites:
      - name: simple-cluster
        driver:
          name: terraform
          root_module_directory: examples/simple-cluster