---
    provisioner:
      name: terraform
    
    verifier:
      name: terraform
      systems:
        - name: inspec-gcp
          backend: gcp
    
    platforms:
      - name: terraform
    
    suites:
      - name: terraform-gcp-cluster
        driver:
          name: terraform
          root_module_directory: fixtures
          parallelism: 4
          command_timeout: 1800