name: kitchen-tests

on: [push, workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            all:
              - '.github/workflows/kitchen-tests.yml'
              - 'Dockerfile'
              - 'Gemfile*'
      - name: Build and Push to Docker Hub
        if: steps.filter.outputs.all == 'true' && !contains(github.event.commits[0].message, '[skip docker]')
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.CCV_DOCKERHUB_USER }}
          password: ${{ secrets.CCV_DOCKERHUB_TOKEN }}
          repository: brownccv/kitchen-terraform
          tags: gcp-cluster
  simple-cluster:
    needs: [docker]
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    container:
      image: brownccv/kitchen-terraform:gcp-cluster
    steps:
    - uses: actions/checkout@v2
    - name: Create Credential File
      run: |
        echo "$GCP_CREDENTIAL_JSON" > /tmp/credentials.json
      env:
        GCP_CREDENTIAL_JSON: ${{ secrets.GCP_CREDENTIAL_JSON}}
    - name: Run Kitchen
      run: kitchen test simple-cluster
      env:
        TF_VAR_github_organization: BrownUniversity
        TF_VAR_github_token: ${{ secrets.GH_token }}
        TF_VAR_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT }}
        TF_VAR_org_id: ${{ secrets.GCP_ORG_ID }}
        TF_VAR_folder_id: ${{ secrets.GCP_FOLDER_ID }}
        TF_VAR_network_name: "network-01"
        TF_VAR_subnet_name: "subnet-01"
        TF_VAR_routing_mode: "REGIONAL"
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
  brown-modules:
    needs: [docker]
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    container:
        image: brownccv/kitchen-terraform
    steps:
    - uses: actions/checkout@v2
    - name: Create Credential File
      run: |
        echo "$GCP_CREDENTIAL_JSON" > /tmp/credentials.json
      env:
        GCP_CREDENTIAL_JSON: ${{ secrets.GCP_CREDENTIAL_JSON}}
    - name: Run Kitchen
      run: kitchen test brown-modules-cluster
      env:
        TF_VAR_github_organization: BrownUniversity
        TF_VAR_github_token: ${{ secrets.GH_token }}
        TF_VAR_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT }}
        TF_VAR_org_id: ${{ secrets.GCP_ORG_ID }}
        TF_VAR_folder_id: ${{ secrets.GCP_FOLDER_ID }}
        TF_VAR_network_name: "network-01"
        TF_VAR_subnet_name: "subnet-01"
        TF_VAR_routing_mode: "REGIONAL"
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json