name: kitchen-tests

on: [push, workflow_dispatch]

jobs:
  simple-cluster:
    runs-on: ubuntu-latest
    container:
      image: brownccv/kitchen-terraform
    steps:
    - uses: actions/checkout@v2
    - uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{secrets.GIT_CREDENTIALS}}
    - name: Create Credential File
      run: |
        echo "$GCP_CREDENTIAL_JSON" > /tmp/credentials.json
      env:
        GCP_CREDENTIAL_JSON: ${{ secrets.GCP_CREDENTIAL_JSON}}
    - name: Run Kitchen
      run: kitchen test simple-cluster
      env:
        TF_VAR_github_organization: BrownUniversity
        TF_VAR_github_token: ${{ secrets.GH_token }}
        TF_VAR_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT }}
        TF_VAR_org_id: ${{ secrets.GCP_ORG_ID }}
        TF_VAR_folder_id: ${{ secrets.GCP_FOLDER_ID }}
        TF_VAR_network_name: "network-01"
        TF_VAR_subnet_name: "subnet-01"
        TF_VAR_routing_mode: "REGIONAL"
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
  brown-modules:
    runs-on: ubuntu-latest
    container:
        image: brownccv/kitchen-terraform
    steps:
    - uses: actions/checkout@v2
    - uses: fusion-engineering/setup-git-credentials@v2
        with:
        credentials: ${{secrets.GIT_CREDENTIALS}}
    - name: Create Credential File
        run: |
        echo "$GCP_CREDENTIAL_JSON" > /tmp/credentials.json
        env:
        GCP_CREDENTIAL_JSON: ${{ secrets.GCP_CREDENTIAL_JSON}}
    - name: Run Kitchen
        run: kitchen test brown-modules-cluster
        env:
        TF_VAR_github_organization: BrownUniversity
        TF_VAR_github_token: ${{ secrets.GH_token }}
        TF_VAR_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT }}
        TF_VAR_org_id: ${{ secrets.GCP_ORG_ID }}
        TF_VAR_folder_id: ${{ secrets.GCP_FOLDER_ID }}
        TF_VAR_network_name: "network-01"
        TF_VAR_subnet_name: "subnet-01"
        TF_VAR_routing_mode: "REGIONAL"
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json