name: kitchen-tests

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: brownuniversity/terraform-gcp-cluster

jobs:
  terraform_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Credential File
        run: |
          echo "$GCP_CREDENTIAL_JSON" | base64 -d > /tmp/credentials.json
        env:
          GCP_CREDENTIAL_JSON: ${{ secrets.GCP_CI_CREDENTIAL_JSON}}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.2
      - name: Run terraform test
        run: |
          terraform init
          terraform test -filter=tests/test_simple_cluster.tftest.hcl
          terraform test -filter=tests/test_brown_modules.tftest.hcl
        env:
          TF_VAR_billing_account: ${{ secrets.GCP_BURWOOD_BILLING_ACCOUNT }}
          TF_VAR_org_id: ${{ secrets.GCP_ORG_ID }}
          TF_VAR_folder_id: ${{ secrets.GCP_CCV_CI_FOLDER_ID }}
          TF_VAR_network_name: "network-01"
          TF_VAR_subnet_name: "subnet-01"
          TF_VAR_routing_mode: "REGIONAL"
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
