name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: brownccv/kitchen-terraform

    steps:
    - uses: actions/checkout@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Credential File
      run: |
        echo "$GCP_CREDENTIAL_JSON" > /tmp/credentials.json
      env:
        GCP_CREDENTIAL_JSON: ${{ secrets.GCP_CREDENTIAL_JSON}}
    - name: Run Kitchen
      run: kitchen test
      env:
        TF_VAR_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT }}
        TF_VAR_org_id: ${{ secrets.GCP_ORG_ID }}
        TF_VAR_folder_id: ${{ secrets.GCP_FOLDER_ID }}
        TF_VAR_network_name: "network-01"
        TF_VAR_subnet_name: "subnet-01"
        TF_VAR_routing_mode: "REGIONAL"
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json