name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: brownccv/kitchen-terraform

    steps:
    - uses: actions/checkout@v2
    - name: Setup SSH Keys and known_hosts
      env:
        PRIVATE_KEY: ${{ secrets.SSH_KEY_PRIVATE }}
      run: |
        mkdir -p $HOME/.ssh &&
        echo \"$SSH_PRIVATE_KEY\" > $HOME/.ssh/id_rsa &&
        chmod 400 $HOME/.ssh/id_rsa
        
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa"

    - name: Create Credential File
      run: |
        echo "$GCP_CREDENTIAL_JSON" > /tmp/credentials.json
      env:
        GCP_CREDENTIAL_JSON: ${{ secrets.GCP_CREDENTIAL_JSON}}
    - name: Run Kitchen
      run: kitchen test
      env:
        TF_VAR_github_organization: BrownUniversity
        TF_VAR_github_token: ${{ secrets.GH_token }}
        TF_VAR_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT }}
        TF_VAR_org_id: ${{ secrets.GCP_ORG_ID }}
        TF_VAR_folder_id: ${{ secrets.GCP_FOLDER_ID }}
        TF_VAR_network_name: "network-01"
        TF_VAR_subnet_name: "subnet-01"
        TF_VAR_routing_mode: "REGIONAL"
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json